name: Create AWS VPC
on:
  workflow_dispatch:
    inputs:
      project_name:
        type: string
      aws_region:
        type: string
      name_vpc:
        type: string
      block_cidr:
        type: string
      port_payload:
        type: string
    secrets:
      ORG_ADMIN_TOKEN:
        required: true
      PORT_CLIENT_ID:
        required: true
      PORT_CLIENT_SECRET:
        required: true
jobs:
  scaffold-service:
    env:
      ORG_NAME: Labtech-DevOps
    runs-on: ubuntu-latest
    steps:
      - uses: Labtech-DevOps/gha-terraform-network@main
        with:
          portClientId: ${{ secrets.PORT_CLIENT_ID }}
          portClientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          portRunId: ${{ fromJson(inputs.port_payload).context.runId }}
          repositoryName: ${{ fromJson(inputs.port_payload).payload.properties.service_name }}
          cookiecutterTemplate: https://github.com/Labtech-DevOps/cookiecutter-tf-network.git
          blueprintIdentifier: "service"
          organizationName: ${{ env.ORG_NAME }}
