name: Create AWS VPC
on:
  workflow_dispatch:
    inputs:
      project_name:
        type: string
      aws_region:
        type: string
      name_vpc:
        type: string
      block_cidr:
        type: string
      port_payload:
        type: string
    secrets:
      ORG_ADMIN_TOKEN:
        required: true
      PORT_CLIENT_ID:
        required: true
      PORT_CLIENT_SECRET:
        required: true
jobs:
  scaffold-service:
    env:
      ORG_NAME: Labtech-DevOps
    runs-on: ubuntu-latest
    steps:
      - uses: Labtech-DevOps/gha-terraform-network@main
        with:
          portClientId: ${{ secrets.PORT_CLIENT_ID }}
          portClientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          portRunId: ${{ fromJson(inputs.port_payload).context.runId }}
          repositoryName: ${{ fromJson(inputs.port_payload).payload.properties.project_name }}
          portUserInputs: '{
          "cookiecutter_project_name": ${{ fromJson(inputs.port_payload).payload.properties.project_name }},
          "cookiecutter_aws_region": ${{ fromJson(inputs.port_payload).payload.properties.aws_region }},
          "cookiecutter_name_vpc": ${{ fromJson(inputs.port_payload).payload.properties.name_vpc }},
          "cookiecutter_block_cidr": ${{ fromJson(inputs.port_payload).payload.properties.block_cidr }},
          "cookiecutter_availability_zone": ${{ fromJson(inputs.port_payload).payload.properties.availability_zone }},
          "cookiecutter_private_subnets": ${{ fromJson(inputs.port_payload).payload.properties.private_subnets }},
          "cookiecutter_public_subnets": ${{ fromJson(inputs.port_payload).payload.properties.public_subnets }},
          "cookiecutter_enable_nat_gateway": ${{ fromJson(inputs.port_payload).payload.properties.enable_nat_gateway }},
          "cookiecutter_single_nat_gateway": ${{ fromJson(inputs.port_payload).payload.properties.single_nat_gateway }},
          "cookiecutter_enable_vpn_gateway": ${{ fromJson(inputs.port_payload).payload.properties.enable_vpn_gateway }}
          }'
          cookiecutterTemplate: https://github.com/Labtech-DevOps/cookiecutter-tf-network.git
          blueprintIdentifier: "service"
          organizationName: ${{ env.ORG_NAME }}
